-- ccdc.ttrd_shch2_auto_withdraw_date definition

CREATE TABLE `ttrd_shch2_auto_withdraw_date` (
  `AUTO_WITHDRAW_DATE` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='自动提款日表';

-- ccdc.ttrd_shch2_withdraw_log definition

CREATE TABLE `ttrd_shch2_withdraw_log` (
  `WITHDRAW_LOG_ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '提款记录ID',
  `QRY_OUT_SID` decimal(19,0) DEFAULT NULL COMMENT '结息信息查询输出表主键',
  `CASH_ACCT_NUM` varchar(15) DEFAULT NULL COMMENT '参与者账号',
  `CASH_ACCT_NAME` varchar(100) DEFAULT NULL COMMENT '参与者简称',
  `EXT_ACCT_NUM` varchar(15) DEFAULT NULL COMMENT '提款账户账号',
  `EXT_ACCT_NAME` varchar(600) DEFAULT NULL COMMENT '提款账户名称',
  `WITHDRAW_AMT` decimal(18,2) DEFAULT NULL COMMENT '提款金额（元）',
  `ACTIVE_WITHDRAW_PATH_NUM` varchar(100) DEFAULT NULL COMMENT '主动提款路径',
  `MEM_ACTIVE_WITHDRAW_NUM` varchar(100) DEFAULT NULL COMMENT '会员主动提款编号',
  `WITHDRAW_TIME` datetime(3) DEFAULT NULL COMMENT '提款时间',
  `WITHDRAW_RESULT` varchar(100) DEFAULT NULL COMMENT '提款结果（0：失败，1：成功）',
  `WITHDRAW_FAILURE_REASON` varchar(500) DEFAULT NULL COMMENT '失败原因',
  `PS` varchar(1000) DEFAULT NULL COMMENT '附言',
  `IS_AUTO_WITHDRAW` varchar(100) DEFAULT NULL COMMENT '是否自动提款（0：否，1：是）',
  PRIMARY KEY (`WITHDRAW_LOG_ID`),
  KEY `TTRD_SHCH2_WITHDRAW_LOG_WITHDRAW_LOG_ID_IDX` (`WITHDRAW_LOG_ID`) USING BTREE,
  KEY `TTRD_SHCH2_WITHDRAW_LOG_QRY_OUT_SID_IDX` (`QRY_OUT_SID`,`WITHDRAW_RESULT`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COMMENT='提款记录表';