DELETE FROM nws.dict WHERE DICT_TYPE IN ('SQ_TRADE_STATUS', 'SQ_SETTLE_CONFIRM_STATUS', 'SQ_TRADE_KIND', 'SQ_TRADE_SRC', 'SQ_BOND_BAL_DIRECTION', 'SQ_BOND_TITLE_CODE', 'SQ_PRINCIPAL_AND_COUPON_TYPE', 'SQ_WITHDRAW_PATH', 'SQ_WITHDRAW_ACCOUNT', 'SQ_TRADE_DEAL_STATUS', 'SQ_SHCH_TRADE_STATUS', 'SQ_PROC_STATUS', 'SQ_EXCEP_STATUS', 'SQ_CLEAR_KIND', 'SQ_CLEAR_NETTING_TYPE', 'SQ_SETTLE_MODE', 'SQ_BOND_TRADE_TYPE', 'SQ_CLEAR_MODE', 'SQ_INTRST_SETTLEMENT_TYPE', 'SQ_SETTLE_ORDER_STATUS');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_STATUS', '0', '待检查', '上清-交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_STATUS', 'CY', '要素检查通过', '上清-交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_STATUS', 'CN', '要素检查不通过', '上清-交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_STATUS', 'C', '待确认', '上清-交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_STATUS', 'R', '已撤销', '上清-交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_STATUS', 'Y', '已确认', '上清-交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_STATUS', 'N', '已拒绝', '上清-交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_STATUS', 'X', '作废', '上清-交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_CONFIRM_STATUS', 'C', '待确认', '上清-买卖方结算确认状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_CONFIRM_STATUS', 'N', '无需确认', '上清-买卖方结算确认状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_CONFIRM_STATUS', 'Y', '已确认', '上清-买卖方结算确认状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_CONFIRM_STATUS', 'X', '已拒绝', '上清-买卖方结算确认状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_KIND', '4', '现券买卖', '上清-交易品种', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_KIND', '10', '买断式回购', '上清-交易品种', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_KIND', 'F', '分销', '上清-交易品种', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_SRC', 'IMIX', '外汇交易中心来源', '上清-交易来源', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_SRC', 'ICLI', '内部客户端来源', '上清-交易来源', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_BAL_DIRECTION', '0', '借方', '上清-余额方向', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_BAL_DIRECTION', '1', '贷方', '上清-余额方向', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TITLE_CODE', '11', '可用', '上清-证券科目代码', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TITLE_CODE', '12', '待付', '上清-证券科目代码', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TITLE_CODE', '13', '全额待购回', '上清-证券科目代码', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TITLE_CODE', '14', '冻结', '上清-证券科目代码', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TITLE_CODE', '15', '质押', '上清-证券科目代码', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TITLE_CODE', '16', '净额待购回', '上清-证券科目代码', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TITLE_CODE', '17', '待行权', '上清-证券科目代码', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TITLE_CODE', '21', '已发行', '上清-证券科目代码', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '1', '分期偿还除本', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '2', '提前赎回除本', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '3', '手动兑付兑息除本', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '4', '提前赎回减券', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '5', '投资人回售', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '6', '周期付息', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '7', '到期还本付息', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '8', '承销费收付', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PRINCIPAL_AND_COUPON_TYPE', '9', '现金分红', '上清-兑付兑息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_WITHDRAW_PATH', '001', '大额汇兑', '上清-主动提款路径', 'SYSTEM', now(), 'SYSTEM', now(), '大额汇兑 001', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_WITHDRAW_ACCOUNT', '100000000180016', '国家开发银行债券净额保证金户', '上清-提款账户账号', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_DEAL_STATUS', 'F', '成交', '上清-交易成交状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_DEAL_STATUS', '4', '撤销', '上清-交易成交状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_TRADE_DEAL_STATUS', '5', '调整', '上清-交易成交状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'C', '待确认', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'Y', '已确认', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'X', '已拒绝', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'AS', '代理测算中', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'AC', '代理已确认', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'N', '无需确认', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'AW', '待代理测算', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'AX', '代理已拒绝', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'CD', '已撤销', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SHCH_TRADE_STATUS', 'WA', '待代理确认', '上清-买卖方交易状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PROC_STATUS', 'N', '无需执行', '上清-处理状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PROC_STATUS', '0', '待执行', '上清-处理状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PROC_STATUS', 'S', '执行成功', '上清-处理状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PROC_STATUS', 'F', '执行失败', '上清-处理状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_PROC_STATUS', '1', '执行中', '上清-处理状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_EXCEP_STATUS', '0', '正常', '上清-异常状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_EXCEP_STATUS', '1', '异常', '上清-异常状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_CLEAR_KIND', 'NCB', '现券买卖净额', '上清-清算品种', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_CLEAR_KIND', 'NOR', '买断式回购净额', '上清-清算品种', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_CLEAR_NETTING_TYPE', 'BOND', '债券净额', '上清-清算轧差类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_MODE', '0', 'DVP-券款对付', '上清-结算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_MODE', '4', 'PAD-见券付款', '上清-结算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_MODE', '5', 'DAP-见款付券', '上清-结算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_MODE', '6', 'DVD-券券对付', '上清-结算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_MODE', '7', 'FOP-纯券过户', '上清-结算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_MODE', '8', 'BLDAP-返券付费解券', '上清-结算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_MODE', '9', 'BLDVP-券费对付', '上清-结算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_MODE', '11', 'NDVP-净额券款对付', '上清-结算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'T', '交易券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'P', '质押券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'G', '保证券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'I', '调入券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'O', '调出券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'B', '借贷券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'E', '外部债券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'EB', '外部债券-借贷券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_BOND_TRADE_TYPE', 'EG', '外部债券-保证券', '上清-债券交易类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_CLEAR_MODE', 'N', '净额清算', '上清-清算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_CLEAR_MODE', 'G', '全额结算', '上清-清算方式', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_INTRST_SETTLEMENT_TYPE', '1', '正常结息', '上清-结息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_INTRST_SETTLEMENT_TYPE', '2', '人工销户结息', '上清-结息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_INTRST_SETTLEMENT_TYPE', '3', '接口销户结息', '上清-结息类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', '0', '应履行', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', '1', '交割中', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', '2', '截止中', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', '8', '成功', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'D', '违约', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'DY', '违约已成', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'B', '待处置', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'BY', '已处置', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'C', '延迟交付', '上清-结息净额结算指令状态类型', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'CY', '延迟交付已成', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'X', '作废', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'CT', '中央债券借贷截止中', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');
INSERT INTO nws.dict
(DICT_TYPE, DICT_KEY, DICT_VALUE, DICT_DESCRIPTION, CREATOR, CREATE_DATETIME, UPDATER, UPDATE_DATETIME, NOTE_ONE, NOTE_TWO, NOTE_THR)
VALUES('SQ_SETTLE_ORDER_STATUS', 'F', '失败', '上清-净额结算指令状态', 'SYSTEM', now(), 'SYSTEM', now(), '', '', '');